name: Publish pytest-tcpclient

on:
  #push:
  #  tags:
  #    - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
jobs:
    publish:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.8"]
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Run tox
          run: make tox
        - name: Publish
          run: make publish
